name: Daily build
on:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)
  workflow_dispatch:

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      nugetVer: ${{ steps.nbgv.outputs.NuGetPackageVersion }}
      asmVer: ${{ steps.nbgv.outputs.AssemblyFileVersion }}
      infoVer: ${{ steps.nbgv.outputs.AssemblyInformationalVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Nerdbank.GitVersioning
        id: nbgv
        uses: dotnet/nbgv@v0.4.2

  daily-build:
    needs: [determine-version]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [linux_x64, win_x64, osx_x64, osx_arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore
      run: |
        chmod +x build.sh
        ./build.sh restore --runtime ${{ matrix.rid }}

    - name: Build
      run: |
        ./build.sh publish \
          --runtime ${{ matrix.rid }} \
          --skip restore \
          --version ${{ needs.determine-version.outputs.nugetVer }} \
          --assembly-version ${{ needs.determine-version.outputs.asmVer }} \
          --informational-version ${{ needs.determine-version.outputs.infoVer }}

    - if: ${{ matrix.rid == 'linux_x64' }}
      name: Download libOpenCvSharpExtern.so
      run: |
        git clone https://github.com/b-editor/beutl-native-deps.git
        cp beutl-native-deps/linux-x64/* output/Beutl
        rm -rf beutl-native-deps

    - name: Zip
      run: |
        ./build.sh zip \
          --runtime ${{ matrix.rid }} \
          --skip publish \
          --version ${{ needs.determine-version.outputs.nugetVer }}

    - name: Save
      uses: actions/upload-artifact@v4
      with:
        name: beutl_${{ matrix.rid }}
        path: ./artifacts/
